### PR TITLE
Change baselines structure

### PR DESCRIPTION
**Pull request by Kataderon**
* JIRA TICKET
  * https://adc.luxoft.com/jira/browse/STVCIS-303
  * https://adc.luxoft.com/jira/browse/STVCIS-1234
  * https://adc.luxoft.com/jira/browse/STVCIS-1263

* PURPOSE
  * Use new baselines structure
  * Store baselines of pc
  * Add option for deleting baselines

* TECHNICAL STEPS
  * Run 303-test branch for autotests and 303-blender-test branch for pipelines in manual job

* NOTE FOR REVIEWERS
  * Use this job for launching tests https://rpr.cis.luxoft.com/job/blender_baselines_test/

* RELATED PR'S
  * https://github.com/luxteam/jobs_launcher/pull/69
  * https://github.com/luxteam/rpr_pipelines/pull/253

* REPORTS
  * https://rpr.cis.luxoft.com/job/blender_baselines_test/12

### CODE REVIEW

**Review by Piromancer — CHANGES_REQUESTED** [review]
image
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2523/Test_20Report/
Тикет https://adc.luxoft.com/jira/browse/STVCIS-1263 не пофикшен, baselines render time все еще -0.0

**Review by Piromancer — APPROVED** [review]

**Review by epozine — APPROVED** [review]

**Comment by Kataderon** [comment]
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3657

**Comment by Kataderon** [comment]
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2575/

**Comment by Kataderon** [comment]
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2590/Test_20Report/

**Review by Piromancer — CHANGES_REQUESTED** [review]
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2596/Test_20Report/AMD_RadeonVII-Ubuntu18/Results/Blender28/Camera/report.html
Не подгружаются бейзлайны

**Review by Piromancer — DISMISSED** [review]

**Review by epozine — APPROVED** [review]

**Pull request merged**
